export const CARD_CONTEXT_MENU_WIDTH_PX = 212;
export const CARD_CONTEXT_MENU_ROW_HEIGHT_PX = 35;
export const CARD_CONTEXT_MENU_BASE_HEIGHT_PX = 174;
export const CARD_CONTEXT_MENU_MAX_HEIGHT_PX = 280;
export const CARD_CONTEXT_MENU_VERTICAL_PADDING_PX = 13;
export const CARD_CONTEXT_MENU_SUBMENU_OFFSET_PX = 9;
export const CARD_CONTEXT_MENU_VIEWPORT_MARGIN_PX = 8;
